### ISSUE TITLE
🤔 Getting Authorization headers from the request object & any how to perfom external API calls

### ISSUE THREAD

**Issue by amsabots** [gofiber/recipes#101]
**Getting Authorization headers from the request object & any how to perfom external API calls**

**Code snippet (optional)**

```go
package main

func main() {

}
```
How do i get the authorization headers i.e bearer token or basic auth token passed to the request object.
```go
func handlerFunction(c *fiber.Ctx) error{
//how do i get the bearer token or auth token from context passed in this function

//something like: not real code implementation
c.Headers("Authorization")

return c.Status(400).JSON(fiber.Map{"error":true, "message":"We cannot map your request to any available api system"})
//return c.JSON(fiber.Map{"message":"The developer can freely hit this api endpoint"});
	
}
```

One last thing, Please note that i come from nodejs and i have got lots of experience in that area, and am stuck at this section where am supposed to an API call and attach data to just like am used with axios module in Nodejs e.g
```javascript
// Make a GET request for a user with a given ID
axios.get('/user?ID=12345')
  .then(function (response) {
    // handle success
    console.log(response);
  })

//Making a POST Request
axios.post('/user', {
    firstName: 'Fred',
    lastName: 'Flintstone'
  })
  .then(function (response) {
    console.log(response);
  })
  .catch(function (error) {
    console.log(error);
  });

//making a POST request with authentication headers
axios.post('/user', {
    firstName: 'Fred',
    lastName: 'Flintstone'
  },
headers: {
      Authorization: `Basic ${Buffer.from(
        `${accountId}:${apiKey}`
      ).toString("base64")}`,
    },
)
  .then(function (response) {
    console.log(response);
  })
  .catch(function (error) {
    console.log(error);
  });
```
**just a recap**
- How to get request authorization infomation from the headers
- How to perfom API fetch request

**Comment by koddr** [comment]
Hi, @amsabots 

You can use this help function to get `Bearer` token from Headers:

```go
func extractToken(c *fiber.Ctx) string {
	bearToken := c.Get("Authorization")

	// Normally Authorization HTTP header.
	onlyToken := strings.Split(bearToken, " ")
	if len(onlyToken) == 2 {
		return onlyToken[1]
	}

	return ""
}
```

**Comment by amsabots** [comment]
> Hi, @amsabots
> 
> You can use this help function to get `Bearer` token from Headers:
> 
> ```go
> func extractToken(c *fiber.Ctx) string {
> 	bearToken := c.Get("Authorization")
> 
> 	// Normally Authorization HTTP header.
> 	onlyToken := strings.Split(bearToken, " ")
> 	if len(onlyToken) == 2 {
> 		return onlyToken[1]
> 	}
> 
> 	return ""
> }
> ```

Hey man thanks... worked like charm
