### ISSUE TITLE
🤔  in the csrf, embed package is not found in golang

### ISSUE THREAD

**Issue by simonqiang** [gofiber/recipes#115]
**  in the csrf example, embed package is not found in golang**

can you advice how to resolve this ? 

```go
import (
	"embed" // this package is not in GOROOT
	"fmt"
	"log"
	"net/http"
	"os"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/template/html"
	"main/routes"
)
```

**Comment by Jictyvoo** [comment]
Afaik embed package comes with Go 1.6, so if you want to use it, upgrade your Go.
Otherwise, you can just remove the import line

**Comment by hi019** [comment]
In addition to what @Jictyvoo said, make sure you are using Go modules. The main Fiber README installation instructions has more info - make sure you do the `go mod init` command.
