### ISSUE TITLE
Recipe for Client 🔥 

### ISSUE THREAD

**Issue by hhuseyinpay** [gofiber/recipes#118]
**Is your feature request related to a problem?**
No.
**Describe the solution you'd like**
Can you add a recipe for the [client](https://docs.gofiber.io/api/client)? There are examples for functions in the doc but it would be great if there is a complete example with best practices.

**Describe alternatives you've considered**

**Additional context**

**Comment by ReneWerner87** [comment]
@kiyonlin could you do this

anyone else can do this of course, pull requests are always welcome

**Comment by alfuhigi** [comment]
@hhuseyinpay  I hope this usefull. according to `client_test.go` [here ](https://github.com/gofiber/fiber/blob/master/client_test.go) we can use client someting like this , If there is no docs you can check all *_test.go , this advice from @ReneWerner87  
```go

package main

import (
	"encoding/json"
	"github.com/gofiber/fiber/v2"
)

type User struct {
	ID       uint
	Fullname string
	Email    string
	Phone    string
	Client   string
}

type Error struct {
	Msg string
}

func main() {
	app := fiber.New()
	app.Post("/create", func(c *fiber.Ctx) error {
		var request User
		err := c.BodyParser(&request)
		if err != nil {
			panic(err)
		}
		args := fiber.AcquireArgs()
		args.Set("fullName", request.Fullname)
		args.Set("email", request.Email)
		args.Set("phone", request.Phone)
		args.Set("client", request.Client)

		a := fiber.Post("http://localhost:3800/api/account/create").Form(args)
		code, body, _ := a.String()
		if code == fiber.StatusOK {
                       // server  return OK 200 
			json.Unmarshal([]byte(body), &request)
			return c.JSON(request)
		}
                // server not OK mean  bad request 400
		var msg Error
		json.Unmarshal([]byte(body), &msg)
		return c.JSON(msg)
	})
	app.Listen(":3801")
}

```
` [Warning] client is still in beta, API might change in the future!`
