### ISSUE TITLE
MongoDB Example for Fiber 🔥

### ISSUE THREAD

**Issue by dhruvStoryDigital** [gofiber/recipes#12]
**Is your feature request related to a problem?** No

**Describe the solution you'd like** MongoDB Recipe

**Describe alternatives you've considered** NA

**Additional context** I want to use MongoDB with Fiber.

**Comment by koddr** [comment]
@dhruvStoryDigital hi!

You feel free to open PR with this recipe 👍

**Comment by tsvetan-ganev** [comment]
@koddr, I was just playing with MongoDB and Fiber yesterday, so I can make a simple example which will mirror the Postgres one.

**Comment by Fenny** [comment]
@dhruvStoryDigital https://github.com/gofiber/recipes/blob/master/mongodb/main.go by @tsvetan-ganev
