### ISSUE TITLE
What is purpose of "binding" in clean-architecture example? 🤔 

### ISSUE THREAD

**Issue by LennyLip** [gofiber/recipes#141]
```
type Book struct {
	ID     primitive.ObjectID `json:"id"  bson:"_id,omitempty"`
	Title  string             `json:"title" binding:"required,min=2" bson:"title"`
	Author string             `json:"author" bson:"author,omitempty"`
}
```
[link](https://github.com/gofiber/recipes/blob/master/clean-architecture/pkg/entities/book.go#L8)

Is it used by fiber or has it to be replaced with "validate" or just removed?

**Comment by ReneWerner87** [comment]
@DarthBenro008

**Comment by ReneWerner87** [comment]
https://github.com/gin-gonic/gin/blob/57ede9c95abb4bc39f471b101181eb06938b5d7f/binding/default_validator.go#L95

looks like this is a copy and paste error, because binding normally belongs to the validator of gin

maybe he transferred his gin project to fiber and then forgot to remove this tag from the entities

**Comment by ReneWerner87** [comment]
@DarthBenro008 is that right ? can you adjust that ?

**Comment by DarthBenro008** [comment]
Ah yes! My bad, that is right, the project was originally in `Gin` and was migrated to gofiber in order to assess performance gains, hence the entities were common, will send a PR adjusting that!

**Comment by ReneWerner87** [comment]
ok, thx

**Comment by LennyLip** [comment]
Thanks for the update! AFAIK using tags in the domain model is not so "clean" anyway. 
But I have another question for now. 
You added the [present laye](https://github.com/gofiber/recipes/blob/master/clean-architecture/api/presenter/book.go#L10)r and it is great. And I think how we can follow DRY principles in this case, I mean rewriting presenter model.
1) there is no inherits in golang
2) composition breaks current example (too much code to rewriting)
3) As a result I ended up with the idea of using [coiper](https://github.com/jinzhu/copier) to convert the domain model to the presenter model.  Is it a good idea or there are better options to use in presenters and controllers?

**Comment by ReneWerner87** [comment]
@DarthBenro008

**Comment by LennyLip** [comment]
Some code for example:

[api](https://github.com/gofiber/recipes/tree/master/clean-architecture/api)/[presenter](https://github.com/gofiber/recipes/tree/master/clean-architecture/api/presenter)/book.go

```
import (
        ...
	"github.com/jinzhu/copier"
)

type BookPresenter struct {
	ID     primitive.ObjectID `json:"id" copier:"must"`
	Title  string             `json:"title" copier:"must"`
}

func BookSuccessResponse(data *domain.Book) *fiber.Map {
	book := BookPresenter{}
	copier.Copy(&book, &data)
        .....
```

[api](https://github.com/gofiber/recipes/tree/master/clean-architecture/api)/[handlers](https://github.com/gofiber/recipes/tree/master/clean-architecture/api/handlers)/book_handler.go

```
import (
        "github.com/go-playground/validator/v10"
	"github.com/jinzhu/copier"
        ...
)

type BookBody struct {
	ID     primitive.ObjectID `json:"id" copier:"must"`
	Title  string             `json:"title" validate:"required,min=1" copier:"must"`
}

func AddBook(service usecases.BookUseCase) fiber.Handler {
	return func(c *fiber.Ctx) error {
		var requestBody BookBody

		err := c.BodyParser(&requestBody)
		if err != nil {
			c.Status(http.StatusBadRequest)
			return c.JSON(presenter.BookErrorResponse(err))
		}

		validate := validator.New()
		if err := validate.Struct(requestBody); err != nil {
			return c.Status(fiber.StatusBadRequest).JSON(err.Error())
		}
		var book domain.Book
		copier.Copy(&book, &requestBody)
		// remove ID due it's a new object
		book.ID = primitive.ObjectID{}

                // NB: I return domain.Book object here, not id
		result, err := service.InsertBook(&book)

		if err != nil {
			c.Status(http.StatusInternalServerError)
			return c.JSON(presenter.BookErrorResponse(err))
		}
		return c.JSON(presenter.BookSuccessResponse(result))
	}
}
```
