### ISSUE TITLE
🤔 Should we use Fist(&user) instead of Find(&user) in the getUserByEmail and getUserByUsername in the handler package?

### ISSUE THREAD

**Issue by salleh** [gofiber/recipes#149]
**Question description**
Using the test `if err := db.Where(&model.User{Username: u}).Find(&user).Error; err != nil {...}` will not produce the intended result. We expect that this will return error = gorm.ErrRecordNotFound if username does not exist in the database. However, this will never happen if we use Find(). The behaviour is true if we use First(&user) instead.

When I tried to use the original code, I failed to properly authenticate a user... I was scratching my head for hours why I got 'unknown' as the returned UserData. Made some reading about the ErrRecordNotFound requirements and someone pointed to me to use First instead of Find function for this purpose. So I made the changes as below and viola! the code works.

**Code snippet (optional)**

```
func getUserByEmail(e string) (*model.User, error) {
	db := database.DB
	var user model.User
	if err := db.Where(&model.User{Email: e}).First(&user).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, nil
		}
		return nil, err
	}

	return &user, nil
}
```

**Comment by norazlan** [comment]
or you can use these
```
res := db.Limit(1).Find(&user, "email = ?", e)
if res.RowsAffected != 1 {
   return nil, nil`
} 
```
