### ISSUE TITLE
hello world

### ISSUE THREAD

**Issue by hilitf** [gofiber/recipes#15]
Hi,
I think there's a mistake in the recipes repository in the hello-world file:
https://github.com/gofiber/recipes/blob/master/hello-world/main.go

In the website (https://docs.gofiber.io/) and in the main github page (https://github.com/gofiber/fiber)  the app.Get command is: app.Get(**"/",** func(c *fiber.Ctx)
But in the receipt it's:  app.Get(**"/hello",** func(c *fiber.Ctx)  - which did not work for me

**Comment by thomasvvugt** [comment]
Hey @hilitf 
The Hello World example serves a Hello World message at `http://localhost:3000/hello` by default.
You're correct that this is somewhat inconsistent in comparison with the examples in our documentation repository.
Let me know if this answers your question!

**Comment by Fenny** [comment]
@hilitf thanks for your issue, I fixed the example!
