### ISSUE TITLE
🤔 how to Graceful restart in Fiber 

### ISSUE THREAD

**Issue by dmskys** [gofiber/recipes#162]
how to Graceful restart in Fiber ？Hope to receive the signal, shut down gracefully, and restart the process, how to use this https://github.com/cloudflare/tableflip  Graceful restart & zero downtime deploy for Go servers.

like gin graceful restart https://gin-gonic.com/docs/examples/graceful-restart-or-stop/

**Comment by linbuxiao** [comment]
Done. Wait PR merged.

**Comment by dmskys** [comment]
thanks
