### ISSUE TITLE
Please update the Fiber version on each go.mod file🐞 

### ISSUE THREAD

**Issue by gaby** [gofiber/recipes#171]
I have recently try to test Fiber using several examples, and it was until an hour later I noticed my error was because all the examples on this repo are using a `go.mod` file with old versions of Fiber.

I would be really helpful if all the examples were updated to the most recent version of Fiber.

**Comment by hi019** [comment]
Dependabot should be handling this. I'll look into it later this week.

**Comment by gaby** [comment]
Thanks! One example is this one: https://github.com/gofiber/recipes/blob/master/stream-request-body/go.mod

From my understanding dependabot only scans the root of the repo, not subdirectories. 

Rel: https://github.com/dependabot/dependabot-core/issues/2178 https://github.com/dependabot/dependabot-core/issues/2824

**Comment by gaby** [comment]
@hi019 Any updates on this?

**Comment by gaby** [comment]
Yes, I will submit a PR for this soon

**Comment by gaby** [comment]
PR has been submitted to close this issue.
