### ISSUE TITLE
🤔 User Login System and Admin Area

### ISSUE THREAD

**Issue by UlasSAYGINIM** [gofiber/recipes#173]
**Question description**
I am looking middlewares and builtin modules, it makes me confused.
how i can implement user login and session management system with gofiber without any problem.
i am not askin JWT api, because it is not complete solution. i am asking about web page login system with administration by admins.

which functions and middlewares i should use in order to create secure system.
i want to use postgresql as database and i may use key/value storage.

in my opinion,
from i learnt gofiber docs.
i may use cookie encryption, i can send session_id to cookie.
and i can save user agent and ip address in postgresql database,
this will give opportunity to tracking sessions and expire them when it is needed.
loginsession system i call it for only tracking useragent , ipv4,ipv6 and date of session created, and expired.
i also thinkg that on services which provided to user,
will also track, which session_id did the operation on user services.
it may also give opportunity to take back some actions.

now i am asking your ideas, which middlewares and builtin functions should be used and how.
which way it will be logical and hardened system for most of the attacks.

I am planing to publish my work , maybe it can be used as a recipe.

**Code snippet (optional)**

```nothing rings a bell.
```

**Comment by gaby** [comment]
Still valid, would be really useful to have an example like this

**Comment by UlasSAYGIN** [comment]
is there any body who can share code example for this need.
