### ISSUE TITLE
Bug in Login flow of auth-jwt section of the gofiber/recipes🐞 

### ISSUE THREAD

**Issue by ADILZAMAL** [gofiber/recipes#2212]
**Fiber version/commit**
v2
**Issue description**
In the Login flow of auth-jwt section of the gofiber/recipes we call `getUserByEmail`, currently we are not returning nil user if user is not found in the db.
**Expected behavior**
We should return nill as User if email is not found in the db.
**Steps to reproduce**
1.Login with a random email which is not present in the db.
**Code snippet**

```go
package handler
func getUserByEmail(e string) (*model.User, error) {
	db := database.DB
	var user model.User
	if err := db.Where(&model.User{Email: e}).Find(&user).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, nil
		}
		return nil, err
	}
	return &user, nil
}
```

**Comment by ADILZAMAL** [comment]
Yeah sure.

**Comment by yogenpoonudurai** [comment]
Hi, is this issue still active? I would like to help.

**Comment by ReneWerner87** [comment]
@yogenpoonudurai ok thx

**Comment by yogenpoonudurai** [comment]
Hi, @ReneWerner87, 
I was unable to push my branch to the repo. Please help to add the necessary permission. Thanks.

**Comment by ReneWerner87** [comment]
You need to create a fork

https://docs.github.com/en/get-started/exploring-projects-on-github/contributing-to-a-project

**Comment by yogenpoonudurai** [comment]
Sorry, my bad. Thanks a bunch.

**Comment by yogenpoonudurai** [comment]
PR raised.
