### ISSUE TITLE
🤔A not immutable question about examples

### ISSUE THREAD

**Issue by axiaoxin** [gofiber/recipes#37]
**Question description**

The examples are great, but I have a question here.

Some places in the sample code use variables to save the value of `c.Params` And then pass these parameters to other functions. Won't there be the problem of `not immutable` mentioned in the fiber document?

**Code snippet (optional)**

<https://github.com/gofiber/recipes/blob/master/gorm/book/book.go#L25>

```go
func GetBook(c *fiber.Ctx) {
	id := c.Params("id")
	db := database.DBConn
	var book Book
	db.Find(&book, id)
	c.JSON(book)
}

```

**Comment by Fenny** [comment]
As long you stay within the context ( fiber.Handler ) it should be no problem. If you pass the parameters outside the context you should copy it before returning from the handler ( sync functions should be no problem )
