### ISSUE TITLE
🔥 URL shortener [Gofiber + Redis]

### ISSUE THREAD

**Issue by amalshaji** [gofiber/recipes#42]
**Is your feature request related to a problem?** No

**Describe the solution you'd like** URL shortener

**Describe alternatives you've considered** NA
 
**Additional context** A simple URL shortener with Gofiber and Redis

**Comment by Fenny** [comment]
That sounds like a good recipe, I'm currently busy with `v1.15.0` and do not have much time to create one. PR's are welcome!

**Comment by amalshaji** [comment]
merged
