### ISSUE TITLE
More websocket examples? 🔥 

### ISSUE THREAD

**Issue by rebootcode** [gofiber/recipes#5]
**Is your feature request related to a problem?**
Yes

**Describe the solution you'd like**

More Websockets example like:

- Room feature
- Custom Connection ID generator option for each new connection.

**Describe alternatives you've considered**
- neffos (https://github.com/kataras/neffos)

**Comment by Fenny** [comment]
Hi @rebootcode, we use the gorilla `Conn` https://github.com/gorilla/websocket/tree/master/examples, feel free to create a PR!
