### ISSUE TITLE
Why Use the RemoveDomainError Helper function ?🤔 

### ISSUE THREAD

**Issue by Ghvstcode** [gofiber/recipes#77]
**Question description**
Hello, I am curious about the RemoveDomainError function! Why not use the [Contains](https://golang.org/pkg/strings/#Contains) function from the string package to check if the URL provided by the user contains the domain name! Also, amazing work.

**Comment by hi019** [comment]
cc @amalshaji

**Comment by amalshaji** [comment]
Yes, you can do that. I didn't know the function existed until now. Also, it's better to validate on the client-side using javascript. Thanks.

**Comment by Ghvstcode** [comment]
Great!

**Comment by amalshaji** [comment]
@Ghvstcode Indeed `DomainError` is very expensive compared to `strings.Contains`

```bash
goos: windows
goarch: amd64
BenchmarkContains-8     145114680                7.33 ns/op
BenchmarkComplex-8       2879019               431 ns/op
PASS
ok      _/D_/Workspace/golang/bench-contains    3.471s
```

But the problem with Contains is that it'll also restrict URL slugs(eg: `https://example.com/blog/stoyle.me-is-a-url-shortener-in-go`). Better to use Regex. Thanks for spotting it.
