### ISSUE TITLE
🔥 OAuth server example.

### ISSUE THREAD

**Issue by hsblhsn** [gofiber/recipes#79]
It will be really nice and helpful if you add an OAuth server example with fiber.

Thank you!

**Comment by joshrahman** [comment]
+1

Would be nice to see a third party provider like [auth0 example](https://auth0.com/docs/quickstart/webapp/golang/01-login) so that the recipe can show using both sessions and jwt along with fiber.

**Comment by securisec** [comment]
+1

Would be nice to see a third party provider like auth0 example so that the recipe can show using both sessions and jwt along with fiber.

**Comment by firewater** [comment]
+1 Yes, please. Pretty please... with a cherry on top ^_^

**Comment by hi019** [comment]
Do you mean implementing the OAuth2 protocol in Fiber? That would be a lot of work and should be done in a dedicated Golang package.

**Comment by firewater** [comment]
Hm, @hsblhsn may have to clarify his request. I was thinking it would be helpful to have a recipe that demonstrates how to use OAuth2 to authenticate users of our web application.

**Comment by hsblhsn** [comment]
@firewater yes! I am requesting an example/recipe to see how to use oAuth2 to authentic users of our web application.

The recipe should have these as a minimum list of features.

1. Authenticate the user.
2. Use session cookie and/or JWT.
3. See a secret page while authenticated.
4. Sign out.


And it will be really helpful to include some third party auth providers like auth0.

Thank you!

**Comment by hi019** [comment]
> 
    Authenticate the user.
    Use session cookie and/or JWT.
    See a secret page while authenticated.
    Sign out.

I have all of these except for sign out in this example - https://github.com/hi019/session-example . I'll add sign out at some point. Until then PR's are welcome!

> And it will be really helpful to include some third party auth providers like auth0.

I agree, an example for managed authentication services would be useful. We'll have to write our own session verification logic because these services provide only net/http packages. Someone made a fasthttp auth0 example here - https://github.com/apibillme/auth0

**Comment by securisec** [comment]
> services provide only net/http packages

Yep! Thats why the adaptor middleware is handy, but I know it is not recommended for prod, so some good examples will be really handy.

**Comment by hi019** [comment]
I'm been busy, PR's are welcome :)

**Comment by vietlib** [comment]
can you provide refresh token feature
