### ISSUE TITLE
Vue.js🔥 

### ISSUE THREAD

**Issue by firewater** [gofiber/recipes#81]
I would love to see a recipe showing how to connect Vue.js, as the front-end Javascript framework, to Go Fiber. With some guidance, I am willing to help write the recipe. We could also create a recipe showing how to use Vuex and Fiber.

**Comment by irenebaluis** [comment]
Hi. I also love the idea. As of now, I am also working on my Financial Management System usinh Gofiber and Vue.js 2 with Typescript and Vuex

**Comment by firewater** [comment]
Wow it sounds like you have a lot of experience using Go Fiber and Vue.js. Are you willing to share your knowledge with us by writing a basic recipe showing how to use Fiber and Vue/Vuex?

**Comment by irenebaluis** [comment]
I've been working with Gofiber and Vue.js for 3 months. I'm just a newbie
also and I'm not really sure if I am doing it very well but my system is
working. Yes, I might work on the recipes if they will accept it. 😁

**Comment by hi019** [comment]
I don't use Vue, but your Fiber app would be just another API endpoint, so you should be able to guides like [this](https://dev.to/firstclown/how-to-query-your-api-using-vuex-in-your-vue-application-11c8) one. 

I only know of one maintainer that is familiar with Vue, I will ask them if they could review a PR for this.

**Comment by amalshaji** [comment]
Well, you could demo three examples

- Rendered using Fiber(the index.html is rendered using Fiber and then VueJs takes over)
- Fiber + Vue Same Origin
- Fiber + Vue Cross-Origin
