### ISSUE TITLE
Deprecated  Recipe from gRPC Side

### ISSUE THREAD

**Issue by muratmirgun** [gofiber/recipes#889]
Since the package used in the example here has been deleted or hidden by the user, the code example is invalid, I would like to delete it for now and write a new one myself if necessary.

Link Here: 
https://github.com/gofiber/recipes/tree/master/fiber-grpc

**Comment by efectn** [comment]
We don't need to remove it. Looks like someone forgot changing module path. We can change it to https://github.com/gofiber/recipes/blob/master/fiber-grpc/proto/service.pb.go#L253

**Comment by muratmirgun** [comment]
I can take this issue
What I mean is the closed package part here
https://github.com/gofiber/recipes/blob/9a93d984284e58715a32050b4d557a82aae125ec/fiber-grpc/server/main.go#L7

**Comment by efectn** [comment]
I know. It's equal to `github.com/amalshaji/fiber-grpc/proto`

**Comment by efectn** [comment]
Looks like module name is also wrong https://github.com/gofiber/recipes/blob/master/fiber-grpc/go.mod#L1

**Comment by muratmirgun** [comment]
yep, I am fixing it! I will send PR!
