### ISSUE TITLE
🔥 What about a new go 1.16 embedded FS example?

### ISSUE THREAD

**Issue by frederikhors** [gofiber/recipes#93]
What about a new go 1.16 embedded FS example?

**Comment by hi019** [comment]
Filesystem MW was just merged in https://github.com/gofiber/fiber/pull/1189. Should be straightforward, PR's welcome :)

As for the static MW, it's being discussed- https://github.com/gofiber/fiber/issues/1190.

**Comment by hi019** [comment]
There is also https://github.com/gofiber/fiber/pull/1175

**Comment by frederikhors** [comment]
> There is also [gofiber/fiber#1175](https://github.com/gofiber/fiber/pull/1175)

Is it online in docs? I cannot see it now.

**Comment by hi019** [comment]
Unfortunately right now our docs are spread across our Gitbook (docs.gofiber.io) and Github markdown. In this case you can find the updated docs at https://github.com/gofiber/fiber/tree/master/middleware/filesystem
